### ISSUE TITLE
Various security improvements

### ISSUE THREAD

**Issue by nashe** [routman/passphrase.io#2]
Aloha,

Just some thoughts on your project, some of them may be wrong (but I'll try to give arguments for each point).

- How to find a way to prove that the files you include (CryptoJS and most especially jQuery, which is not really necessary and you are not even using the last one) are not _backdoored_? They are minified but not your script. In case of your server being compromised, what can guarantee they're not modified?

- The “load-the-content-as-you-type” is a nice example of a functionality ruining the security. Even with the current `setTimeout()` value, I think. It have been already said that it gives the capability to an attacker (after finding your private key used for SSL, I admit) to be able to bruteforce more easily the hashes, which are ONLY `sha256(key)`.

- The brainwallet case showed us that \*just\* SHA256 should not be used for key derivation. See https://rya.nc/cracking_cryptocurrency_brainwallets.pdf :^)

- Nearly the same proble: the hash used as index for the database is only based on the password of the document. What about weak passwords or just enumeration of pastes using dictionaries? (no rate-limiting for the `gettext.php` page). Thus, why not introduce a kind of salt? Like a pseudonym, or one random unique value to remind in addition of the password you choose…

- The password is displayed without any kind of protection. Why not at least hide it using small `*`? For the same reasons that a lot of known and audited tools are doing it for decades.

- Directory listing is enabled (see https://passphrase.io/js/). Since this repository does not contain the whole source code of your service, maybe it's possible to find other accessible folders and use the directory listing to _steal things_ (we don't know anything about your backend - maybe it's just files and it would become very easy to dump all the files to attack the hashes of the whole database offline). It takes one line to disable it on Apache.

- Can you provide the source code for `gettext.php` and `savetext.php`? We all know that this language is often _error-prone_ and it would still be interesting to have it in this repository. It seems that the welcome message is fetched from the database by using `e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855` (`== sha256('')`) as index and it's not possible to change it using a POST to `savetext.php`. Using a `null` byte inside the index causes the request to timeout, I'm wondering why. 

- What kind of data are you visualizing on https://passphrase.io/stats/? What do you collect as user information while the service is running?

- And about the CSP, what do you think of using  ```Content-Security-Policy: "default-src 'none'; script-src 'self'; style-src 'self' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; connect-src 'self'"``` and exclude the calls to `fonts.googleapis.com` in a near future?

Edit: Added something about the key derivation function and the CSP header.

**Comment by nashe** [comment]
And about the CSP, what do you think of using `
Content-Security-Policy: "default-src 'none'; script-src 'self'; style-src 'self' https://fonts.googleapis.com; font-src https://fonts.gstatic.com; connect-src 'self'"` and exclude the calls to `fronts.googleapis.com` in a near future?

**Comment by routman** [comment]
Hello nashe,

I greatly appreciate the thoughtful notes you have provided on the security concerns of passphrase.io.  I have been very busy with other things so it has taken me along time to respond, but passphrase.io has gone through some significant changes over the past few months and I believe I have finally addressed the concerns that you have brought up.  

#1: All javascript files have been consolidated to a single file.  You can easily verify file integrity by computing a checksum.

#2, 3, 4: Passphrase.io now uses the scrypt KDF instead of just one round of SHA256.  No more “load-the-content-as-you-type”.  This offers significant security improvements over the original version.  Please see the "technical details" section on the home page for more details.

#5: Your passphrase can now be masked by clicking the "hide passphrase" button at the top.

#6: Directory listing has been disabled.  Thanks for pointing that out.

#7: I prefer not to publish the server-side code, as I believe it would make it easier for sophisticated attackers to find loopholes and compromise the server.  However, as you could imagine, they are very simple scripts and there have been no issues so far.  

#8: I have since moved the website to a new server, and stats are no longer collected.  My previous server had stats enabled by default.

#9: The fonts are locally hosted now, so no external calls to the google API is made.

Again, I appreciate your feedback.  You inspired me to put effort into making passphrase.io more secure.

**Comment by nashe** [comment]
Awesome @routman, good work! 

For me and (I guess) a lot of people, not having the server-side code of one open-source project is a "no-go". We can discuss of this is in another issue, but there are numerous reasons to publish it instead of relying on obscurity to be secure.
